# Julia基本用法
## 数据类型
此处列举在julia中定义的几种常用数据类型，整数型（默认Int64）、浮点数型（默认Float64）、bool型、复数型、有理数型、字符串型

In [29]:
var1 = 4 #整数型
var2 = 1.4 #浮点数型
var3 = true #bool型
var4 = 1+4im #复数型
var5 = 3//6 #有理数型
var6 = "Hello world !" #字符串型
typeof(var4)# typeof() 函数查看某个变量类型，例如查看变量var6的数据类型

Complex{Int64}

通过科学计数法来定义类型

In [21]:
var7 = 1e5

100000.0

有理数型会自动约分

In [9]:
3//6

1//2

也可以显式定义变量类型 (如非必要，减少使用静态数据类型)

In [50]:
var8 = Float64(3.3)
var9 = Float32(3.3)
typeof(var9)

Float32

指数运算 ^
<br>
复数取共轭 conj()

In [69]:
print(2^10,"\n",conj(3+4im))

1024
3 - 4im

## 数组（Array）
在julia中，存储运算大量数据通常通过数组这一类型变量进行，一般地，定义一个数组使用
<br>
Array{Type,Dimension}()函数，其中Type是数组中数据的类型，Dimension是数组的维数,可缺省。
<br>
如定义一个4x3的复矩阵

In [54]:
Mat1 = Array{ComplexF64,2}(undef,4,3)#花括号中ComplexF64代表Float64构成的复数，圆括号中第一个变量是初值，undef为随机分配初值，后面的4和3分别代表行数与列数
Mat2 = Array{Float64}(undef,4,3)

4×3 Matrix{Float64}:
 6.93465e-310  6.93465e-310  6.93465e-310
 6.93465e-310  6.93465e-310  6.93465e-310
 6.93465e-310  6.93465e-310  6.93465e-310
 6.93465e-310  6.93465e-310  6.93466e-310

In [55]:
Mat3 = Array{Union{Missing,ComplexF64}}(missing,4,3)#初值也可赋为missing

4×3 Matrix{Union{Missing, ComplexF64}}:
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing

常用的初值矩阵可用如下几个函数定义：
<br>
1. ones() 所有元素初值为1
2. zeros() 所有元素初值为0
3. rand() 所有元素为0-1的随机数

In [51]:
Mat3 = ones(5,5)
Mat4 = zeros(6,4)
Mat5 = rand(4,7)

4×7 Matrix{Float64}:
 0.51002   0.790329  0.603015  0.135097   0.463799  0.65435   0.405808
 0.296736  0.382992  0.017665  0.0389416  0.458599  0.680139  0.588871
 0.696319  0.390714  0.782442  0.135574   0.168493  0.564841  0.9639
 0.651901  0.617858  0.349564  0.522479   0.798723  0.467362  0.526742

单位矩阵可通过导入 LinearAlgebra 包定义
<br>
Matrix{Type}(I,row,rank)

In [53]:
using LinearAlgebra
Matrix{Float64}(I,4,6)

4×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0

## 矩阵运算及一些常用操作
矩阵加法减法只需要两个矩阵维数相同即可
<br>
矩阵乘法 A*B 需要A的列与B的行相同
<br>
矩阵除法 $$A/B = A*B^{-1}$$
需要A的列与B的列相同

In [72]:
Mat1 = ones(4,5)+rand(4,5)
Mat2 = ones(4,5)-rand(4,5)
Mat3 = ones(7,5)*rand(5,3)
Mat4 = ones(7,5)/rand(3,5)

7×3 Matrix{Float64}:
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109
 0.0413633  2.14257  0.14109

结合广播算符（fused broadcasting operator）/或称 dot call
<br>
对于每个二元算符都有对应结合广播算符

In [2]:
Mat5 = rand(4,5).*rand(4,5)
Mat6 = rand(4,5).^rand(4,5)

4×5 Matrix{Float64}:
 0.620528  0.808866  0.925746  0.456114  0.403386
 0.571615  0.16892   0.792767  0.470652  0.595126
 0.832963  0.580344  0.879369  0.882266  0.996824
 0.991316  0.945705  0.976998  0.95068   0.268059

宏 @. expr 将表达式中所有函数都转化为dot call

In [13]:
x=1.0:3.0; y=similar(x)

3-element Vector{Float64}:
 6.92463467891766e-310
 6.9246346790054e-310
 6.9246325480869e-310

In [24]:
@. y= x+3*sin(x)

3-element Vector{Float64}:
 3.5244129544236893
 4.727892280477045
 3.4233600241796016

### LinearAlgebra库
使用LinearAlgebra中dot函数计算两个向量的内积（点积）

In [27]:
dot(rand(5),rand(5))

2.045945111809508

如果dot(x,y)中变量为复数，则会输出
$$ x^\star \cdot y$$

In [33]:
a = rand(ComplexF64,5)
b = rand(ComplexF64,5)

5-element Vector{ComplexF64}:
  0.5553158462580637 + 0.4080977035786577im
   0.815726643350133 + 0.1817877452806942im
  0.2908366669333948 + 0.842348619983765im
 0.04371263227814093 + 0.7534567281148052im
  0.9301461069920232 + 0.5505071717047341im

In [34]:
dot(a,b)

2.160778666277288 - 0.3067941603560356im

In [37]:
sum(conj(a).*b)

2.160778666277288 - 0.3067941603560355im

向量叉乘

In [52]:
cross([0,1,0],[1,0,0])

3-element Vector{Int64}:
  0
  0
 -1

求矩阵本征值与本征向量

In [40]:
A = rand(5,5)
eigvals(A)

5-element Vector{ComplexF64}:
 -0.6162873041815338 + 0.0im
 0.14114067777420836 - 0.33284267485866076im
 0.14114067777420836 + 0.33284267485866076im
  0.6244598885850129 + 0.0im
   2.756555898369448 + 0.0im

In [41]:
eigvecs(A)

5×5 Matrix{ComplexF64}:
   0.728941+0.0im  …   -0.619748+0.0im  0.353761+0.0im
  -0.649687+0.0im      -0.208456+0.0im  0.409107+0.0im
  -0.045982+0.0im     -0.0687021+0.0im   0.48641+0.0im
   0.207944+0.0im       0.669445+0.0im  0.332245+0.0im
 -0.0345963+0.0im       0.345807+0.0im  0.600419+0.0im

In [46]:
val1 = eigvals(A)[1]
vec1 = eigvecs(A)[:,1]

5-element Vector{ComplexF64}:
   0.7289412730054067 + 0.0im
  -0.6496866409892732 + 0.0im
 -0.04598204995622316 + 0.0im
  0.20794382170098383 + 0.0im
 -0.03459634558078485 + 0.0im

In [47]:
A* vec1/val1

5-element Vector{ComplexF64}:
     0.728941273005407 - 0.0im
    -0.649686640989271 - 0.0im
  -0.04598204995622259 - 0.0im
   0.20794382170098422 - 0.0im
 -0.034596345580784046 - 0.0im

求矩阵的逆

In [48]:
inv(A)

5×5 Matrix{Float64}:
 -1.27515    -1.91131   -0.0551419  -6.24244     5.76631
  0.917836   -0.697624  -0.504281   -0.312028    0.762929
  0.636997    1.51187    0.585677    2.48617    -2.96176
  0.0199354   1.84096   -0.44066     3.51992    -2.65615
 -0.460158   -0.65044    0.812143    0.0917187   0.368398

In [49]:
A*inv(A)

5×5 Matrix{Float64}:
  1.0           2.98372e-16  1.38778e-17   1.79544e-16  -4.71845e-16
  1.43982e-16   1.0          5.37764e-17  -4.6187e-17   -1.05645e-15
  5.55112e-17   0.0          1.0          -4.996e-16    -5.55112e-17
  1.11022e-16  -1.11022e-16  0.0           1.0          -2.498e-16
 -1.11022e-16  -1.11022e-16  1.11022e-16  -4.996e-16     1.0

In [53]:
det(A) #求A的本征值
tr(A) #求A的迹
transpose(A) #对A转置

5×5 transpose(::Matrix{Float64}) with eltype Float64:
 0.30602    0.755614   0.445033  0.179832   0.690488
 0.990775   0.394249   0.379185  0.558988   0.958548
 0.811488   0.931598   0.965574  0.0242772  0.523756
 0.0552738  0.716658   0.11833   0.617786   0.919697
 0.0807629  0.0131324  0.864853  0.676997   0.763381

## 逻辑运算

In [56]:
x= true
y = false
!x #非运算符，true->false, false->true
x && y #与运算符，当两个表达式都为true时返回true,否则返回false
x || y #或运算符，当两个表达式都为false时返回false,否则返回true

true

判断语句

In [57]:
x = 4
y = 7
x == y #等于判断
x != y #不等于判断
x < y #小于判断
x > y #大于判断
x <= y #小于等于判断
x >= y #大于等于判断

false

In [64]:
x = Inf #Infinity
y = NaN #Not a Number
z = NaN
isequal(y,z) #判断y与z是否同一

true

In [65]:
z == y

false

In [66]:
isinf(x) #判断是否是无穷大
isfinite(x) #判断是否是有限数

true

? 表达式，  expression ? value1 : value2
<br>
判断表达式是否为真，如果为真返回value1， 否则返回value2

In [68]:
x > y ? 3 : 5

5

## 字符串常用操作

In [76]:
a = "Hello world!"
b = "Happy birthday!"

"Happy birthday!"

对字符串中元素的索引

In [83]:
lastindex(a) #字符串最后一个下标
firstindex(a) #字符串第一个下标
a[2:7] #索引弟2-7个元素
a[begin] #索引第一个元素
a[end] #索引最后一个元素

'!': ASCII/Unicode U+0021 (category Po: Punctuation, other)

In [84]:
a[end-1]

'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)

In [95]:
string(a,' ',b) #拼接a b两个字符串
a*' '*b #另一种方式拼接两个字符串

"Hello world! Happy birthday!"

在字符串中对变量进行引用

In [96]:
age = 50
name = "Brown"

"Brown"

In [97]:
"My name is $name, I'm $age years old now!" #在字符串中通过$var来引用变量

"My name is Brown, I'm 50 years old now!"

In [106]:
"I have \$100" #在字符串中输出$需要在前面添加\作为反转译字符

"I have \$100"

In [108]:
print("I have \$100") # 在print函数中显示正常

I have $100

In [110]:
Word = "Python is a programming language"
replace(Word,"Python"=>"Julia","language"=>"languages")

"Julia is a programming languages"

对字符串进行切割

In [111]:
a = "here,you,are,my,there"

"here,you,are,my,there"

In [112]:
split(a,',') #split(string,sep)

5-element Vector{SubString{String}}:
 "here"
 "you"
 "are"
 "my"
 "there"

对字符串进行修饰（去除字符串收尾多余的内容）

In [113]:
a = "[this is my house! \n]"

"[this is my house! \n]"

In [115]:
strip(a,['[',']','\n'])

"this is my house! "

## 函数

定义一个函数

In [119]:
function foo(x,y)
    x = y*20
    y = x+2
    x,y
end

foo (generic function with 1 method)

In [122]:
x_out,y_out = foo(4,5)

(100, 102)

一种更简单的语法定义函数

In [128]:
foo1(x) = 4x+2

foo1 (generic function with 1 method)

In [129]:
foo1(3)

14

In [130]:
foo2(x,y) = x^4+8,y^3 #定义多变量函数

foo2 (generic function with 2 methods)

In [131]:
foo2(30,30)

(810008, 27000)

### 函数返回值

In [132]:
function foo3(x)
    return x^3
    x^2
end

foo3 (generic function with 1 method)

In [133]:
foo3(10)

1000

### 类型声明

In [134]:
function foo4(x)::Int16  #声明返回值类型
    x
end

foo4 (generic function with 1 method)

In [135]:
y = foo4(10)
typeof(y)

Int16

In [136]:
function foo5(x::Int64) #声明参数类型
    x
end

foo5 (generic function with 1 method)

In [137]:
foo5(6.3)

LoadError: MethodError: no method matching foo5(::Float64)
Closest candidates are:
  foo5(::Int64) at In[136]:1

map 函数用法

In [140]:
x_mat = collect(1:0.1:10)
map(foo1,x_mat)

91-element Vector{Float64}:
  6.0
  6.4
  6.8
  7.2
  7.6
  8.0
  8.4
  8.8
  9.2
  9.6
 10.0
 10.4
 10.8
  ⋮
 37.6
 38.0
 38.4
 38.8
 39.2
 39.6
 40.0
 40.4
 40.8
 41.2
 41.6
 42.0

In [141]:
foo1.(x_mat)

91-element Vector{Float64}:
  6.0
  6.4
  6.8
  7.2
  7.6
  8.0
  8.4
  8.8
  9.2
  9.6
 10.0
 10.4
 10.8
  ⋮
 37.6
 38.0
 38.4
 38.8
 39.2
 39.6
 40.0
 40.4
 40.8
 41.2
 41.6
 42.0

In [142]:
map(x->4x^2+3,x_mat)

91-element Vector{Float64}:
   7.0
   7.840000000000001
   8.76
   9.760000000000002
  10.84
  12.0
  13.240000000000002
  14.559999999999999
  15.96
  17.439999999999998
  19.0
  20.64
  22.360000000000003
   ⋮
 319.84000000000003
 327.0
 334.23999999999995
 341.55999999999995
 348.96000000000004
 356.44000000000005
 364.0
 371.64
 379.35999999999996
 387.1600000000001
 395.04
 403.0

可选参数

In [143]:
function foo(x,y=6)
    x+y
end

foo (generic function with 2 methods)

In [145]:
foo(3)
foo(3,9)

12

关键字参数 赋值时只能通过关键字进行赋值

In [146]:
function foo1(x ; y_key_value = 9)
    x + y_key_value
end

foo1 (generic function with 1 method)

In [147]:
foo1(3,5)

LoadError: MethodError: no method matching foo1(::Int64, ::Int64)
Closest candidates are:
  foo1(::Any; y_key_value) at In[146]:1

In [148]:
foo1(3,y_key_value=5)

8

## 控制流(Control flow)

begin end 语句

In [149]:
z = begin
    x = 3
    y = 4
    x+y
end

7

变量的作用域

In [150]:
begin
    local_x = 4
    local_y = 8
    local_x + local_y
end

12

if 语句

In [159]:
x = 15
if x >0
    print("x is a positive number")
elseif x==0
    print("x is zero")
else
    print("x is a negtive number")
end

x is a positive number

### While 语句

In [161]:
x = 0 
while x<10
    x = x+1
    print(x,"\n")
end

1
2
3
4
5
6
7
8
9
10


### break函数用法

In [162]:
x = 0
while x<10
    x = x+1
    if x > 5
        break
    end
    print(x,"\n")
end

1
2
3
4
5


### continue 函数用法

In [163]:
x = 0
while x<10
    x = x+1
    if x<5
        continue
    end
    print(x,"\n")
end

5
6
7
8
9
10
